# python 3.10 base image
FROM python:3.10-slim

# install git
RUN apt-get update && apt-get install -y git

# set up app directory
WORKDIR /app

# install python packages
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# add app code
COPY . .

# add extra packages
RUN pip install git+https://github.com/MIDORIBIN/langchain-gpt4free.git
RUN pip install -U langchain-community

# add gunicorn
RUN pip install gunicorn

# open port 5000
EXPOSE 5000

# start app with gunicorn
CMD ["gunicorn", "-b", "0.0.0.0:5000", "main:app"]