# Use an official Python runtime (Python 3.11)
FROM python:3.11-slim

# Install necessary system dependencies including git and curl
RUN apt-get update && apt-get install -y git curl

# Set the working directory in the container
WORKDIR /app

# Copy the backend code into the container
COPY . /app

# Download the wait-for-it.sh script
RUN curl -o /app/wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh

# Make wait-for-it.sh executable
RUN chmod +x /app/wait-for-it.sh

# Install the backend dependencies from requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Install additional dependencies
RUN pip install git+https://github.com/MIDORIBIN/langchain-gpt4free.git
RUN pip install -U langchain-community

# Install Gunicorn
RUN pip install gunicorn

# Expose port 5000 for the backend service
EXPOSE 5000

# Run Gunicorn, waiting for PostgreSQL to be ready
CMD ["./wait-for-it.sh", "postgres-svc:5432", "-t", "30", "--", "gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "main:app"]